version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: notes-app
    ports:
      - '3030:3030'
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: notesapp
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: pnpm run start:dev

  postgres:
    image: postgres:15-alpine
    container_name: notes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesapp
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: notes-adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
